name: Lint
on:
  push:
    branches:
      - main
      
  pull_request:
    branches:
      - main

jobs:
  Analyze:
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false

    steps:
      - name: Checkout Repository  
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install Pyright
        run: |
          pip install "pyright[nodejs]>=1.1.393,<2"

      - name: Lint Codebase
        run: |
            