name: Lint
on:
  push:
    branches:
      - main
      - dev
      
  pull_request:
    branches:
      - main
      - dev

jobs:
  Analyze:
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false
      matrix:
        version: ['3.12', '3.13']

    steps:
      - name: Checkout Repository  
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.version }}

      - name: Install Tox
        run: |
          pip install "tox>=4.24.1,5"

      - name: Lint Codebase
        run: |
          RAW_PYTHON_VERSION=${{ matrix.version }}
          PYTHON_VERSION=$(echo $RAW_PYTHON_VERSION | sed 's/\.//')
          tox -e py$PYTHON_VERSION
            